### ISSUE TITLE
Launching xVASynth's interface is not necessary

### ISSUE THREAD

**Issue by Pendrokar** [esyx-git/SML#1]
`<xVASynth>C:\Path\To\xVASynth.exe</xVASynth>`
xVASynth.exe launches the Web Front-end, which in turn launches the back-end server.exe that Mantella contacts.

Mantella will try to run server.exe on its own, if it cannot contact xVASynth.

So unless Herika starts to use xVASynth, there is no need to run the interface which only consumes extra resources.

If you still plan to run the backend, it can be run from the Command Prompt like this:
```
CPU
C:\Games\steamapps\common\xVASynth>.\resources\app\cpython_cpu\server.exe

GPU
C:\Games\steamapps\common\xVASynth>.\resources\app\cpython_gpu\server.exe
```

**Comment by esyx-git** [comment]
Pendrokar, 

Thank you for bringing this issue to light.

I originally wrote this to be general enough so that the xVASynth tag should be able to accept either back-end executable, as well as the front-end, depending on the user's needs. To the same end, .bat files should also work for the LLM and Herika tags. 

Regardless, I did not realize Mantella's functionality for xVASynth when I initially wrote this. I will create a use tag for xVASynth, thus making it optional, and update the documentation to explain the functionality I mentioned initially in this comment.

I will comment with an update and close this issue upon completion.

**Comment by esyx-git** [comment]
I have released a new version to address this issue.
